resources:
  pipelines:
    - pipeline: ciPipeline  
      source: Pipeline-Ci  

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
- template: common-variables.yml

steps:
- task: DownloadPipelineArtifact@2
  displayName: 'Download Artifact from CI Pipeline'
  inputs:
    source: Pipeline-Ci
    path: '$(Pipeline.Workspace)/drop'


- task: UseDotNet@2
  displayName: 'Install .NET SDK 8.0'
  inputs:
    packageType: 'sdk'
    version: '8.0.x'
    installationPath: $(Agent.ToolsDirectory)/dotnet

- task: AzureRmWebAppDeployment@4
  displayName: 'Deploy to Azure Web App'
  inputs:
    azureSubscription: $(azureSubscription)
    appType: 'webApp'
    WebAppName: $(appServiceName)
    packageForLinux: '$(Build.ArtifactStagingDirectory)/drop/publish.zip'